version: '3'

services:
  laravel_messenger:
    container_name: laravel_messenger
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    restart: always
    ports:
      - "8000:8888"
    command: >
      sh -c "
      composer install &&
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8888
      "
    depends_on:
      - mysql_messenger
    networks: ["stack"]

  frontend:
    container_name: komnaty-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm run build && npm run preview"
    ports:
      - "4173:4173"
    networks: ["stack"]

  mysql_messenger:
    image: mysql:latest
    container_name: mysql_messenger
    environment:
      - MYSQL_ROOT_PASSWORD=Vbnz
      - MYSQL_DATABASE=messenger
    volumes:
      - ../storage/dbvolume:/var/lib/mysql
    networks: ["stack"]



  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d
    networks: ["stack"]


  soketi:
    image:  quay.io/soketi/soketi:0.34-16-debian
    container_name: soketi
    ports:
      - "6001:6001"
      - "9601:9601"
    networks: ["stack"]

networks:
  stack:
    driver: bridge

