version: '3'

services:
 laravel_messenger:
   container_name: laravel_messenger
   build:
     context: ./backend
     dockerfile: Dockerfile
   volumes:
     - ../:/var/www
   restart: always
   ports:
     - "8000:8888"
   command: >
     sh -c "
     php /var/www/artisan migrate &&
     php /var/www/artisan serve --host=0.0.0.0 --port=8888
     "
   depends_on:
     - mysql_messenger
   networks: ["stack"]

     
  frontend:
    container_name: komnaty-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '4173:4173'
    command: bash -c "npm run build && npm run preview"
    networks: ["stack"]


 mysql_messenger:
   image: mysql:5.7
   container_name: mysql_messenger
   environment:
     - MYSQL_ROOT_PASSWORD=Vbnz
     - MYSQL_DATABASE=messenger
   volumes:
     - ../storage/dbvolume:/var/lib/mysql
   networks: ['stack']


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
   networks: ['stack']


  soketi:
    command: bash -c "docker run -p 6001:6001 -p 9601:9601 quay.io/soketi/soketi:1.4-16-debian -d"
    networks: ['stack']

networks:
  stack:
    driver: bridge

